### PR TITLE
Solution for 175. Combine Two Tables

### LINKED ISSUE #1: Calling out all the SQL-enthusiasts
_**

- Add the question - from leetcode in readme.md and also add the link to the question.
- Add the solution to solution.sql
- Explain your solution (optional)

**_

### PR DESCRIPTION
**Pull request by pakosel**
Resolves #1

### CODE REVIEW

**Comment by thesprydatasnake** [comment]
@pakosel Can you add the leetcode question link to the readme?

**Comment by pakosel** [comment]
> @pakosel Can you add the leetcode question link to the readme?

@thesprydatasnake - the link has been added

**Comment by pakosel** [comment]
@thesprydatasnake - Hacktoberfest page displays "Project not participating error" at my contribution to this repo. Can you please clarify on this? Thanks,
image

**Comment by thesprydatasnake** [comment]
Wait for a day, and let me know if it still shows that.

**Pull request merged**
